# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [6]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [9]:
planet = "Earth"
diameter = 12742

In [11]:
line=" The diameter of {planet} is {diameter} kilometers".format(planet="Earth" , diameter=12742)
print(line)

 The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [59]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d

{'k1': [1,
  2,
  3,
  {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}

In [60]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [31]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [33]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
b=np.ones(10)*5
print(b)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [40]:
b=np.arange(20,35,2)
print(b)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [47]:
c=np.arange(0,9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a+b
print(c)

[5 7 9]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [49]:
import pandas as pd


In [54]:
data=[['sri',"male",'good'],['tamil',"male","bad"]]
a=pd.DataFrame(data,columns=['name','gender','char'])
a

name gender  char
0    sri   male  good
1  tamil   male   bad

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [55]:
pd.date_range(start='01/01/2023',end='10/02/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [63]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [65]:
df=pd.DataFrame(lists,columns=['num','char','num2'])
df

num char  num2
0    1  aaa    22
1    2  bbb    25
2    3  ccc    24